name: CI

on: [push, pull_request]

jobs:
  test-src:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use `node` v${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: make test-spec-with-coverage
      - run: make lint-ci
      - run: make test-src-tsc
      - run: make test-src-internal-import-restrictions
      - run: make test-src-does-not-import-dist
      - run: make test-src-scripts-consistency
      - run: make format # note: not in `test-src` in `package.json`, only in CI
      - run: make clean

  test-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use `node` v${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: make build-esm
      - run: make build-bin
      - run: make build-types
      - run: make build-sites
      - run: make build-site-docs
      - run: make clean

  test-dist:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use `node` v${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: make build-esm
      - run: make test-dist-lib-node-import
      - run: make test-dist-lib-perf
      - run: make test-dist-lib-plain-esbuild-compat
      - run: make test-dist-lib-scramble-all-events
      - run: make test-dist-lib-vite
      - run: make test-dist-lib-build-size
      - run: make build-sites
      - run: make test-dist-sites-experiments
      - run: make clean

  test-using-bun:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install # TODO: ieally we'd test that this works without dev deps, but the `--production` flag requires a lockfile.
      - run: bun run src/bin/scramble.ts 333
