name: js.cubing.net

on:
  push:
    branches: [main]

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build-pages:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]

    steps:
      - uses: actions/checkout@v4
        with:
            lfs: 'true'
      - name: Use `node` v${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: make setup
      - run: make build-site-docs
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1 # TODO: update
        with:
          path: ./dist/sites/js.cubing.net/
          retention-days: 1

  deploy-pages:
    runs-on: ubuntu-latest

    needs: build-pages

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    # https://github.com/actions/deploy-pages#usage
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
